<nav>
    <ul>
        <li><a href="index.php" title="Home Page" <?php echo $indexPage; ?> >Home</a></li>
        <li><a href="product.php" title="Product Page" <?php echo $productPage; ?> >Our Products</a></li>
        <li><a href="enquire.php" title="Enquiry Page" <?php echo $enquirePage; ?>>Buy</a></li>
        <li><a href="about.php" title="About Page" <?php echo $aboutPage; ?> >About Us</a></li>
        <li><a href="enhancements.php" title="Enhancements" <?php echo $enhancePage; ?> >Special Features</a></li>
        <li><a href="enhancements2.php" title="Enhancements2" <?php echo $enhance2Page; ?>>Special Features 2</a></li>
        <li><a href="enhancements3.php" title="Enhancements3" <?php echo $enhance3Page; ?>>Special Features 3</a></li>
        <li><a href="manager.php" title="Management" <?php echo $managerPage; ?>>Manager</a></li>
    </ul>
</nav>